### ISSUE TITLE
Make ignition scheduling optional

### ISSUE THREAD

**Issue by andrewchen0028** [Planetary-Soft-Landing-at-Purdue/PSL-with-KSP#4]
https://github.com/Planetary-Soft-Landing-at-Purdue/PSL-with-KSP/blob/1f5ede2cb48fb083c215f8a7061d9ea418b05396/main_control.py#L93-L96

**Comment by JohnBensen1000** [comment]
already optional, pass as key word argument, initialSearch=True, to pdg method
