### ISSUE TITLE
Implement closed-loop solve time optimization

### ISSUE THREAD

**Issue by andrewchen0028** [Planetary-Soft-Landing-at-Purdue/PSL-with-KSP#6]
https://github.com/Planetary-Soft-Landing-at-Purdue/PSL-with-KSP/blob/1f5ede2cb48fb083c215f8a7061d9ea418b05396/main_control.py#L110

**Comment by JohnBensen1000** [comment]
Comment after closing issue, my bad, pdg re-calculates tSolve every 8 pdg calls, stops if there's less than 10 seconds until touchdown
